### ISSUE TITLE
1.3.1 Opdater organisation med domænenavne

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#1029]
Når en brugeradmin inviterer en bruger skal der ske en validering af den nye brugers emaildomæne. Domænet skal være på 'tilladt' listen over domæner der er registreret på organisationen

Som en brugeradmin, der inviterer en bruger vil jeg gerne have en validering på den inviterede brugers emailadresse
for at sikre mig, at sikkerheden højnes

Userstory: Mailadresse (validering: indenfor eget domæne)

Man kan registrere sit eget domæne navn. 
I MVP løsning bruges der kun 1 domæne. Domænet kan i MVP ikke ændres efter det er sat.

- [x] Energinetbruger kan registere domænenavn på organisationen.
- [x] Når email-domænet sættes skal det slå igennem med det samme
- [ ] Validering: Domænet må ikke allerede være i brug

Man skal have ret til at kunne redigere en organisation.

Design er ikke lavet, så udvikleren tilføjer feltet på skærmbilledet.

# Tasks
- [x] Opret nyt felt til primær domæne på organisation.
- [x] Udvid oprettelse af organisation med angivelse af domæne.
- [x] Indsæt felt til domæne i frontend. Kun redigerbart under oprettelse.

**Comment by ENDK-RHC** [comment]
Test gennemført og følgende er fundet ok:
Det er ikke muligt at oprette en organisation uden domæne navn
Domæne navn skal følge xxxxxxx.xxx
Der kan ikke oprettes flere organisationer med samme domæne navn.
Det er kan efterfølgende ikke rettes i domæne navn.
