### ISSUE TITLE
2 Flow for accepting invitation link

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/ARCHIVED-geh-post-office#1059]
### Synopsis
Brugeradmin har inviteret en bruger og brugeren har modtaget en mail.
I denne mail skal brugeren kunne acceptere at han oprettes som bruger i Datahub
Skal kobles sammen med 2FA

Som bruger vil jeg
kunne acceptere mailinvitationen
så jeg kan komme videre i processen med at få adgang til datahub
_____________
### Acceptance Criteria
- [ ] Brugeren kan acceptere invitationen
- [ ] 2FA

Note: Ingen krav om PW sikkerhed (kommer i senere opgave)
________________
### Tech. Notes
Create deployment this tenant, application registrations, secrets and this user flow. 
________________
### Task List
- [ ]
- [ ]
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [x] Can be tested?
- [x] Can be demoed?

**Comment by defectiveAi** [comment]
Fra Outlaws: "vi har rakt ud til Cloud Architecture i "store" Energinet vedrørende dette - det er en rettighed der mangler på vores service principal i U-002"
