### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/ARCHIVED-geh-post-office#1069]
### Synopsis
Brugeren har et simpelt password men skal nu dirigeres ind på en side i Datahub hvor han promptes for selv at angive et password
_____________
### Acceptance Criteria
- [ ] Bruger skal lande på en 'landing page' i DataHub
- [ ] Brugeren kan her angive et andet password
________________
### Tech. Notes
________________

### Task List
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
- [ ] Verified by UX

_________________
#### How to test
Enviroment:
User:
Senario:
