### ISSUE TITLE
'Simpelt password'

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#1070]
### Synopsis
Brugeren har accepteret linket  i invitationsmailen og skal have et 'simpelt password' (BTC) som han kan bruge til at tilgå Datahub med.

_____________
### Acceptance Criteria
- [ ] Brugeren får et simpelt password
- [ ] Brugeren har adgang til DataHub
________________
### Tech. Notes
________________

### Task List
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
- [ ] Verified by UX

_________________
#### How to test
Enviroment:
User:
Senario:
