### ISSUE TITLE
Liste over alle brugere, der skal kunne tildeles roller af FAS bruger admin

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#882]
Denne mangler Aktørnavn og GLN.
Se 'Listen over brugere skal også indeholde aktørnavn og GLN#993'

### Synopsis

For at kunne tildele roller til en bruger skal FAS brugeradmin have en liste over brugere
_____________
### Acceptance Criteria
- [x] Som FAS brugeradmin skal jeg kunne se en liste over brugere
- [x] Listen skal indeholde følgende felter: email, navn, telefonnummer, ~roller~, aktørnavn, aktørGLN,, ~aktørmarkedsrolle~, ~oprettelsesdato~, status (aktiv, inaktiv/blokeret)
- [x] Sortering i liste (mjm)

### Noter
Søgning og filtrering er ikke en del af denne opgave.
________________
### Tech. Notes
Serverside paginering
________________
### Task List
- [x] Backend: Expose paginated user API (mail only for now). (xkama, mjm)
- [x] Backend: Create new permission 'users:manage'.
- [x] Frontend: Users page.
- [x] Frontend: Guard page behind 'users:manage'.
- [x] ~Frontend: Add Created column.~ (aiu)
- [x] Backend: Add actor/roles/etc. to returned result. (aiu)
- [x] Frontend: Add actor/roles/etc. columns to user list. (aiu)
- [x] Sortering i liste (mjm)
_________________
#### Testability
- [x] Can be tested?
- [x] Can be demoed?

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=0%3A1&t=UE4MLaPq0X66OSXX-1

![image.png](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/7e24eab7-3cc2-46f3-8215-49e0487d2843)

**Comment by Tm1807** [comment]
Jeg kan ikke teste dette. T-miljø er nede og jeg har ikke de rigtige rettigheder på U1 og U2

**Comment by Tm1807** [comment]
Test godkendt.
Telefonnummer kommer med senere epic (rediger bruger)
