### ISSUE TITLE
Tildeling af roller til brugere som aktør brugeradmin

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#883]
### Synopsis
Som en brugeradmin for en aktør vælger jeg en bruger på listen for at kunne tilføje en brugerrolle til den valgte bruger
___________
### Acceptance Criteria
- [x] Bruttolisten over roller er bestemt af aktørmarkedsrollen
- [x] Brugeradmin skal kunne tildele brugeren en eller flere brugerroller fra bruttolisten
- [x] En brugerrolle skal kun kunne tildeles én gang indenfor den samme aktør/markedsrolle
____________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
