### ISSUE TITLE
Fjernelse af roller fra brugere som aktør brugeradmin

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#885]
### Synopsis
Som en brugeradmin for en aktør vælger jeg en bruger på listen for at kunne fjerne en brugerrolle fra den valgte bruger
___________
### Acceptance Criteria
- [ ] Bruttolisten over roller er bestemt af aktørmarkedsrollen. De allerede tildelte roller er markerede med flueben.
- [ ] Brugeradmin skal kunne fjerne en eller flere brugerroller fra brugeren
____________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
