### ISSUE TITLE
Redigere en brugerrolle

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#891]
### Synopsis
Som FAS brugeradmin skal jeg kunne redigere en brugerroller i DH GUI
___________
### Acceptance Criteria
- [x] Som FAS brugeradmin skal jeg kunne redigere i en brugerrolles navn (validering: ingen dubletter)
- [x] Som FAS brugeradmin skal jeg kunne redigere i en brugerrolles beskrivelse
- [ ] Som FAS brugeradmin skal jeg kunne ændre status (aktiv/inaktiv).
- [ ] Skifte til 'aktiv' er muligt.
- [x] Visning af historik

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=25%3A8317&t=xqdgOppNwM0PXvE9-3
____________
### Tech. Notes
________________
### Task List
- [x] Backend
  - [x] Handler, validation, commands, repository
  - [x] Client
  - [x] Unit tests
- [ ] Frontend
  - [x] BFF
  - [ ] UI (dzu)
    - [x] Editing of user role name (validation: no duplicates, required)
    - [x] Editing of user role description (validation: required field)
    - [x] Notification on successful/error update
    - [ ] ~Editing of user role status~ (**not relevant**)
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?

**Comment by ENDK-RHC** [comment]
Følgende er blevet testet og testet ok.

Som FAS brugeradmin kunne jeg redigere i en brugerrolles navn (validering: ingen dubletter)
Som FAS brugeradmin kunne jeg redigere i en brugerrolles beskrivelse
Der blev vist korrekt historik på historik fanen.

**Comment by Tm1807** [comment]
- Som FAS brugeradmin skal jeg kunne ændre status (aktiv/inaktiv).
 - Skifte til 'aktiv' er muligt.
Bege tages ud og lægges i en anden opgave
