### ISSUE TITLE
[Titans] Roller/rettigheder: 7 Redigering af indholdet af rettigheder i brugerroller

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#892]
### Synopsis

Som en DataHub bruger med korrekte rettigheder skal jeg kunne tilføje eller fjerne rettigheder i eksisterende brugerroller.
For at kunne styre brugerroller/rettigheder.

### Acceptance Criteria
- [ ] 
- [ ]
### Task List
- [ ]
- [ ]
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
- [ ] Verified by UX
#### How to test

Enviroment:User:Senario:

Husk til refinement: De rettigheder man kan se her, skal afgrænses af de markedsroller, som brugerrollen er tilknyttet.
