### ISSUE TITLE
Tildeling og fjernelse af rettigheder i brugerroller

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#893]
### Synopsis

Som en Energinet medarbejder skal jeg kunne indsætte eller fjerne rettigheder i eksisterende brugerroller
For at kunne styre brugerroller/rettigheder - og dermed hvad brugere kan se/udføre i DataHub UI.

### Acceptance Criteria

- [x] Rettigheder kan tildeles til en brugerrolle
- [x] Rettigheder kan fjernes fra en brugerrolle

### Tech. Notes
https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Brugeradministration?node-id=25%3A8332&t=Jrin8TFCkALOn8Xi-1

### Task List
- [x] Add support for setting initially selected rows in `watt-table` component
- [x] Move Permissions table component from "create user role" to a shared place
- [x] Move logic for getting user role permissions to separate store
- [x] Use Permissions table in "edit user role" modal
- [x] Connect the Permissions table with the form
- [x] Add Permissions validation

#### Testability
- [x] Can be tested?
- [x] Can be demoed?
- [x] Verified by UX

#### How to test
- [ ] En bruger med den rigtige rettighed :-) kan i - UI - tildele eller fjerne rettigheder fra en brugerroller og gemme ændringerne.
 Enviroment:User:Senario:
