### ISSUE TITLE
Tildeling af roller til brugere som FAS brugeradmin - historik

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#900]
Kan ikke testes frontend - venter på 884

### Synopsis
Som FAS brugeradmin ønsker jeg at kunne se en historik over ændringer af tildeling af roller
___________
### Acceptance Criteria
Historik skal vises ( med følgende info )
- [x] Tildeling af rolle
- [x] Sletning af rolle
- [x] Hvem har gjort det
- [x] Tidspunkt
____________
### Tech. Notes
________________
### Task List
- [x] Backend (DB, Tests, WepApi) 
   - [x] ChangedByUserId -> read from context
- [x] Update client package with WebApi call (for bff)
- [x] Backend: Add UT for audit entries.
- [x] Frontend, Part 1: Create table filled with correct data.
- [x] Frontend, Part 2: Integrate table into drawer component.
- [x] Frontend, Part 3: Test the component.
_________________
#### Testability
- [x] Can be tested?
- [x] Can be demoed?

![image.png](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/7050e5df-610e-499d-a45a-dba30a53e255)

**Comment by Tm1807** [comment]
Test ok
