### ISSUE TITLE
Liste over brugerroller - historik

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#904]
### Synopsis
Som FAS brugeradmin skal jeg kunne se en liste over eksisterende brugerroller i DH GUI

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=22%3A24014&t=AET9r5IIx5uXUuah-1
___________
### Acceptance Criteria
- [ ] Ved klik på en rolle skal man kunne se detaljer for brugerrollen: historik
- [ ] Hvem har gjort det
- [ ] Tidspunkt
____________
### Tech. Notes

________________
### Task List
- [x] Backend code, db table, client
- [x] Frontend
_________________
#### Testability
- [x] Can be tested?
- [x] Can be demoed?

**Comment by Tm1807** [comment]
Testet ok
