### ISSUE TITLE
Tildeling af roller til brugere som aktør brugeradmin - historik

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#905]
### Synopsis
Som en brugeradmin for en aktør vælger jeg en bruger på listen for at kunne tilføje en brugerrolle til den valgte bruger

Oplæg til historik:
[user] har fjernet brugerrollen [brugerrolle]
[user] har tilføjet brugerrollen [brugerrolle]
___________
### Acceptance Criteria
- [ ] Brugernavn, email, telefonnummer skal vises
- [ ] Kun brugere for den pågældende brugeradmins aktør vises på listen
- [ ] Historik skal vises
____________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=2%3A5682&t=1jEMj44yXg7cwNQX-1
