### ISSUE TITLE
Fjernelse af roller fra brugere som aktør brugeradmin - historik

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#906]
### Synopsis
Som en brugeradmin for en aktør vælger jeg en bruger på listen for at kunne fjerne en brugerrolle fra den valgte bruger

Oplæg til historik:
[user] har fjernet brugerrollen [brugerrolle]
[user] har tilføjet brugerrollen [brugerrolle]

___________
### Acceptance Criteria
- [ ] Historik skal vises

Mangler en definition af hvilke data der skal vises
____________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
