### ISSUE TITLE
Tildeling og fjernelse af rettigheder i roller - historik

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#907]
### Synopsis
Som en Energinet medarbejder skal jeg kunne historik over de rettigheder, der er tilføjet eller fjernet i en brugerrolle
For at opfylde revisionskrav på brugerroller/rettigheder.

### Acceptance Criteria

- [x] Brugerrollens historik viser ændringerne i brugerrollens indhold af rettigheder

### Task List
- [x] Backend til at gemme historik for rettigheder
- [x] Frontend der viser historik for rettigheder

#### Testability
- [x] Can be tested?
- [x] Can be demoed?
- [x] Verified by UX

#### How to test
- [x] En bruger kan - efter at have ændret i rettighederne i en brugerrolle - se ændringerne på fanen: historik

Enviroment:User:Senario:

**Comment by ENDK-RHC** [comment]
RHC - Det er testet ok at historik bliver logget ved oprettelse oprettelse af brugerrolle. Det er endnu ikke mulig at testet om der bliver registret historik ved ændring.
