### ISSUE TITLE
[Titans] (Epic1) Create users with roles/rights: 'FAS'

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/ARCHIVED-geh-post-office#941]
### Synopsis
Til Epic 1 skal der bruges en bruger, der kan tilgå GUI med FAS rettigheder til at se/gøre

_____________
### Acceptance Criteria

- [ ] FAS - bruger

- [ ] Mulighed for at tilknytte rettigheder til de forskellige typer af brugere

### Noter
01-12-2022: Estimeret til 2 sprints
________________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
